## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

codecov: true

os:
  - linux
  - windows

julia:
  - 1.0
  - 1  # latest release
  - nightly

notifications:
  email: false

git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly
